#Fly時の1分辺りの経験値消費量
flyexp: '50'

#ブロックを並べるスキル
blocklineup:
  level: '15'
  mana_mag: '0.0'
  minestack_level: '30'

#範囲設置スキル
ZoneSetSkill:
  level: '15'

#スキルを使って並べた時のブロックカウント倍率
BlockCountMag: '0.2'

# MineStackブロック一括クラフト
minestack_BlockCraft:
  level1: '25'
  level2: '35'
  level3: '45'
  
#ブロック設置カウントの1分上限
BuildNum1minLimit: '100'