name: buildAssist
main: com.github.unchama.buildassist.BuildAssist
version: 0.0.5

commands:
  fly:
      description: This is a fly command.
      usage: /<command> <finish/amount/endless>
      permission-message: You don't have <permission>
      permission: multibuildplugin.build